### ISSUE TITLE
Minor bug in stop-dashboard script

### ISSUE THREAD

**Issue by amcaar** [ufcg-lsd/saps-dashboard#15]
Hi SAPS developers,
I found that the script 'bin/stop-dashboard' is not properly working because of a minor typo in the awk command. You need to use this commas '' instead of ‘‘, so this error appears:

awk: cmd. line:1: ‘{print
awk: cmd. line:1: ^ invalid char '?' in expression

The right line is:
ps xau | grep app.js | awk '{print $2}' | xargs sudo kill

Regards,
Amanda.

**Comment by thiagomanel** [comment]
Thanks for reporting it, @amcaar 

@wesleymonte in addition to fixing this, could you please take a look at the others SAPS script (to check if we propagated the error by copy and paste)
